// Generated by Supabase MCP (2026-01-04). Keep in sync with your Supabase schema.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.1";
  };
  public: {
    Tables: {
      clerk_users: {
        Row: {
          clerk_user_id: string;
          created_at: string;
          email: string | null;
          external_id: string | null;
          first_name: string | null;
          id: string;
          image_url: string | null;
          last_name: string | null;
          last_sign_in_at: string | null;
          linkedin_connected: boolean;
          linkedin_last_checked_at: string | null;
          linkedin_profile: Json | null;
          linkedin_status_message: string | null;
          updated_at: string;
          username: string | null;
        };
        Insert: {
          clerk_user_id: string;
          created_at?: string;
          email?: string | null;
          external_id?: string | null;
          first_name?: string | null;
          id?: string;
          image_url?: string | null;
          last_name?: string | null;
          last_sign_in_at?: string | null;
          linkedin_connected?: boolean;
          linkedin_last_checked_at?: string | null;
          linkedin_profile?: Json | null;
          linkedin_status_message?: string | null;
          updated_at?: string;
          username?: string | null;
        };
        Update: {
          clerk_user_id?: string;
          created_at?: string;
          email?: string | null;
          external_id?: string | null;
          first_name?: string | null;
          id?: string;
          image_url?: string | null;
          last_name?: string | null;
          last_sign_in_at?: string | null;
          linkedin_connected?: boolean;
          linkedin_last_checked_at?: string | null;
          linkedin_profile?: Json | null;
          linkedin_status_message?: string | null;
          updated_at?: string;
          username?: string | null;
        };
        Relationships: [];
      };
      posts: {
        Row: {
          content: string;
          created_at: string;
          id: number;
          image_base64: string | null;
          image_mime_type: string | null;
          linkedin_post_id: string | null;
          published_at: string | null;
          status: string;
          topic: string;
          updated_at: string;
        };
        Insert: {
          content: string;
          created_at?: string;
          id?: number;
          image_base64?: string | null;
          image_mime_type?: string | null;
          linkedin_post_id?: string | null;
          published_at?: string | null;
          status?: string;
          topic: string;
          updated_at?: string;
        };
        Update: {
          content?: string;
          created_at?: string;
          id?: number;
          image_base64?: string | null;
          image_mime_type?: string | null;
          linkedin_post_id?: string | null;
          published_at?: string | null;
          status?: string;
          topic?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Insert: infer I }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Update: infer U }
      ? U
      : never
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;


